### ISSUE TITLE
Breaks when used with a phansible playbook

### ISSUE THREAD

**Issue by netsensei** [geerlingguy/ansible-role-drush#18]
Hi,

I tried using this role in conjunction with a phansible.com generated playbook, but it breaks the provisioning process.

Breaks with this error:

```
TASK [geerlingguy.drush : Create drush symlink.] *******************************
fatal: [192.168.88.88]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert between file and link for /usr/local/bin/drush", "owner": "root", "path": "/usr/local/bin/drush", "size": 5033570, "state": "file", "uid": 0}
```

How to reproduce:

1. Create an ansible profile with phansible.com
2. Install this role through ansible-galaxy: `ansible-galaxy install geerlingguy.drush`
3. Add this role to the playbook.yml (- geerlingguy.drush)
4. Run `vagrant up` (and `vagrant provision` if necessary)

Cause and solution:

In main.yml I had to change the state parameter from 'link' to 'file':

```
- name: Create drush symlink.
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: file
```
