### ISSUE TITLE
Ensure Drush is installed globally via Composer never stops

### ISSUE THREAD

**Issue by dorianboulch** [geerlingguy/ansible-role-drush#56]
I'm using this role but de task `Ensure Drush is installed globally via Composer` never stops.

site.yml
```yml
  roles:
    - role: geerlingguy.composer
      become: true
    - role: geerlingguy.drush
      become: true
```
vars.yml
```yml
drush_composer_global_install: true
drush_composer_update: false
```
